name: Contacts Api Build and Test

on:
  workflow_dispatch: # Enable manual triggering
  push:
    branches:
      - main
    paths:
      - "cloud/apis/contacts-api/**"
  pull_request:
    branches:
      - main
    paths:
      - "cloud/apis/contacts-api/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        name: Checkout code

      - name: List directory contents
        run: |
          ls -R

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9.5.0

      # - name: Cache pnpm modules
      #   uses: actions/cache@v4
      #   with:
      #     path: |
      #       cloud/apis/contacts-api/node_modules
      #     key: ${{ runner.os }}-pnpm-${{ hashFiles('cloud/apis/contacts-api/pnpm-lock.yaml') }}
      #     restore-keys: |
      #       ${{ runner.os }}-pnpm-

      - uses: actions/setup-node@v4
        name: Set up Node.js
        with:
          node-version: "20.x"
          cache: "pnpm"
          cache-dependency-path: cloud/apis/contacts-api/pnpm-lock.yaml

      - name: Install dependencies
        run: |
          cd cloud/apis/contacts-api
          pnpm install

      - name: Run tests
        run: |
          cd cloud/apis/contacts-api
          pnpm test
