name: Contacts Api Build and Test

on:
  workflow_dispatch: # Enable manual triggering
  push:
    branches:
      - main
      - develop
    paths:
      - "cloud/apis/contacts-api/**"
  pull_request:
    branches:
      - main
      - develop
    paths:
      - "cloud/apis/contacts-api/**"

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      actions: write
      contents: read

    steps:
      - uses: actions/checkout@v4
        name: Checkout code

      # Uncomment for debugging
      # - name: List directory contents
      #   run: |
      #     ls -R

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9.5.0

      # An alternative method for caching pnpm dependencies
      # - name: Cache pnpm modules
      #   uses: actions/cache@v4
      #   with:
      #     path: |
      #       cloud/apis/contacts-api/node_modules
      #     key: ${{ runner.os }}-pnpm-${{ hashFiles('cloud/apis/contacts-api/pnpm-lock.yaml') }}
      #     restore-keys: |
      #       ${{ runner.os }}-pnpm-

      - uses: actions/setup-node@v4
        name: Set up Node.js
        with:
          node-version: "20.x"
          cache: "pnpm"
          cache-dependency-path: cloud/apis/contacts-api/pnpm-lock.yaml

      - name: Install dependencies
        run: |
          cd cloud/apis/contacts-api
          pnpm install

      - name: Run tests
        run: |
          cd cloud/apis/contacts-api
          pnpm test

      - name: Build
        run: |
          cd cloud/apis/contacts-api
          pnpm build

      # Uncomment for debugging
      - name: List directory contents
        run: |
          ls -R

      - name: Upload the contacts api build directory as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: contacts-lambda-build-${{ github.ref_name }}
          path: cloud/apis/contacts-api/dist/ # The unzipped build directory

      # - name: Trigger Terraform workflow
      #   run: |
      #     curl -X POST \
      #       -H "Accept: application/vnd.github.v3+json" \
      #       -H "Authorization: token ${{ secrets.WORKFLOW_TOKEN }}" \
      #       https://api.github.com/repos/istashak/volo-accendo/dispatches \
      #       -d '{"event_type": "trigger_terraform_workflow"}, "client_payload": { "ref": "${{ github.ref }}" }}'
